namespace SwipeLab.Domain.DatingProfile.Constants
{
    public static class PromptsConstants
    {
        public static readonly List<DatingProfilePrompt> Prompts = [
            new DatingProfilePrompt { Beginning = "I spend way too much money on", Continuation = "books I'll never finish and snacks I'll never regret." },
            new DatingProfilePrompt { Beginning = "My worst daily enemy is", Continuation = "my alarm clock... and sometimes my fridge." },
            new DatingProfilePrompt { Beginning = "I couldn’t live without", Continuation = "music, memes, and midnight snacks." },
            new DatingProfilePrompt { Beginning = "I think we should spend a day", Continuation = "getting lost in a new city and finding the weirdest museums." },
            new DatingProfilePrompt { Beginning = "My simple pleasures", Continuation = "are rainy days, fresh cookies, and inside jokes." },
            new DatingProfilePrompt { Beginning = "The way to win me over is", Continuation = "through laughter and shared playlists." },
            new DatingProfilePrompt { Beginning = "A random fact I love", Continuation = "is that octopuses have three hearts." },
            new DatingProfilePrompt { Beginning = "When I unplug I like to", Continuation = "get muddy on hikes and stargaze till I can't keep my eyes open." },
            new DatingProfilePrompt { Beginning = "On a lazy afternoon, you’ll find me", Continuation = "building blanket forts and pretending to be productive." },
            new DatingProfilePrompt { Beginning = "I believe that the best conversations happen", Continuation = "after midnight and over cheap pizza." },
            new DatingProfilePrompt { Beginning = "One thing I never leave home without is", Continuation = "a half-charged phone and big dreams." },
            new DatingProfilePrompt { Beginning = "If I were a dessert, I’d be", Continuation = "a slightly chaotic ice cream sundae." },
            new DatingProfilePrompt { Beginning = "My biggest flex is", Continuation = "how many plants I've kept alive (recently)." },
            new DatingProfilePrompt { Beginning = "I judge people based on", Continuation = "how they treat waiters." },
            new DatingProfilePrompt { Beginning = "The silliest thing I believed as a kid was", Continuation = "that quicksand would be a daily problem." },
            new DatingProfilePrompt { Beginning = "The emoji that best represents me is", Continuation = "🦥 (the cozy sloth)." },
            new DatingProfilePrompt { Beginning = "If I were a villain, my evil plan would involve", Continuation = "hiding everyone’s socks." },
            new DatingProfilePrompt { Beginning = "My dream home includes", Continuation = "a secret library and a room just for napping." },
            new DatingProfilePrompt { Beginning = "If my pet could talk, it would probably say", Continuation = "‘Feed me again. I’m starving. Always.’" },
            new DatingProfilePrompt { Beginning = "My favorite excuse to cancel plans is", Continuation = "‘I have a date...with my couch.’" },
            new DatingProfilePrompt { Beginning = "My go-to karaoke song is", Continuation = "anything by Queen, whether I can hit the notes or not." },
            new DatingProfilePrompt { Beginning = "The best fictional universe to live in would be", Continuation = "something with dragons but no taxes." },
            new DatingProfilePrompt { Beginning = "I measure time based on", Continuation = "how far I am from my next snack." },
            new DatingProfilePrompt { Beginning = "I once tried to", Continuation = "learn the ukulele... I can now play two and a half songs." },
            new DatingProfilePrompt { Beginning = "The moment I knew adulthood hit was", Continuation = "getting excited about new sponges." },
            new DatingProfilePrompt { Beginning = "An underrated joy is", Continuation = "cracking open a brand-new notebook." },
            new DatingProfilePrompt { Beginning = "Life’s too short not to", Continuation = "order dessert first." },
            new DatingProfilePrompt { Beginning = "Sundays are for", Continuation = "recharging my soul with coffee and silly adventures." },
            new DatingProfilePrompt { Beginning = "In my pockets you will find", Continuation = "a lucky coin and way too many crumpled receipts." },
            new DatingProfilePrompt { Beginning = "My guilty pleasure", Continuation = "is watching cheesy rom-coms like it's a sport." },
            new DatingProfilePrompt { Beginning = "I could talk for hours about", Continuation = "why dogs are clearly better than cats (fight me)." },
            new DatingProfilePrompt { Beginning = "Right now I’m a huge fan of", Continuation = "mystery novels and tiny cafes." },
            new DatingProfilePrompt { Beginning = "My unusual skills include", Continuation = "whistling really loud and winning at board games." },
            new DatingProfilePrompt { Beginning = "The key to my heart is", Continuation = "great conversation and terrible dance moves." },
            new DatingProfilePrompt { Beginning = "The smell that instantly lifts my mood is", Continuation = "freshly baked bread." },
            new DatingProfilePrompt { Beginning = "I know it’s going to be a good day when", Continuation = "I hear my favorite song by accident." },
            new DatingProfilePrompt { Beginning = "One conspiracy theory I’m willing to believe is", Continuation = "birds aren’t real (prove me wrong)." },
            new DatingProfilePrompt { Beginning = "My biggest irrational fear is", Continuation = "dropping my phone on a rollercoaster." },
            new DatingProfilePrompt { Beginning = "My motto lately is", Continuation = "‘Done is better than perfect.’" },
            new DatingProfilePrompt { Beginning = "A dream date idea I have is", Continuation = "a mini road trip with no destination." },
            new DatingProfilePrompt { Beginning = "The weird hill I’m willing to die on is", Continuation = "cold pizza is better than hot pizza." },
            new DatingProfilePrompt { Beginning = "If I could only eat one meal for the rest of my life, it would be", Continuation = "breakfast for dinner." },
            new DatingProfilePrompt { Beginning = "When I need a mood boost, I", Continuation = "blast 2000s pop and dance like nobody’s watching." },
            new DatingProfilePrompt { Beginning = "If I could teleport anywhere right now, it would be", Continuation = "to a cabin with a crackling fireplace." },
            new DatingProfilePrompt { Beginning = "My cure for melancholy is", Continuation = "laughing until my stomach hurts or baking something slightly chaotic." },
            new DatingProfilePrompt { Beginning = "If I could have dinner with a celebrity, it would be", Continuation = "Keanu Reeves, because calm energy and wild stories are my thing." },
            new DatingProfilePrompt { Beginning = "You’ll never change my mind about", Continuation = "dancing in the kitchen being peak romance." },
            new DatingProfilePrompt { Beginning = "If I could relive one concert it would be", Continuation = "any one where I lost my voice singing and didn’t care." },
            new DatingProfilePrompt { Beginning = "My greatest strengths are", Continuation = "empathy, playlist curation, and parallel parking under pressure." },
            new DatingProfilePrompt { Beginning = "I geek out on", Continuation = "weird history facts and niche internet drama." },
            new DatingProfilePrompt { Beginning = "If I had a warning label, it would say", Continuation = "‘Approach with caffeine.’" },
            new DatingProfilePrompt { Beginning = "The most spontaneous thing I’ve ever done is", Continuation = "join a parade by accident and just keep walking." },
            new DatingProfilePrompt { Beginning = "The thing I secretly love about myself is", Continuation = "my ability to find the humor in awkward silences." },
            new DatingProfilePrompt { Beginning = "I know it's love when", Continuation = "they remember how I take my coffee without asking." },
            new DatingProfilePrompt { Beginning = "An oddly satisfying moment is", Continuation = "peeling the plastic off a new gadget." },
            new DatingProfilePrompt { Beginning = "The best compliment I’ve ever received was", Continuation = "‘You make chaos feel safe.’" },
            new DatingProfilePrompt { Beginning = "My love language is", Continuation = "sending memes that remind me of you." },
            new DatingProfilePrompt { Beginning = "A strange opinion I stand by is", Continuation = "ice cream tastes better eaten with a fork." },
            new DatingProfilePrompt { Beginning = "The soundtrack of my ideal road trip is", Continuation = "a chaotic shuffle between bangers and ballads." },
            new DatingProfilePrompt { Beginning = "If I were a kitchen utensil, I’d be", Continuation = "a spork — confusing but efficient." },
            new DatingProfilePrompt { Beginning = "The most overused phrase in my vocabulary is", Continuation = "‘just one more episode.’" },
            new DatingProfilePrompt { Beginning = "The hill I’ll happily die on is", Continuation = "that brunch is a personality, not a meal." },
            new DatingProfilePrompt { Beginning = "The best smell in the world is", Continuation = "coffee at 7am." },
            new DatingProfilePrompt { Beginning = "The weirdest thing I love is", Continuation = "organizing books by color instead of genre." },
            new DatingProfilePrompt { Beginning = "If I were a holiday, I’d be", Continuation = "Halloween—fun, dramatic, and candy-fueled." },
            new DatingProfilePrompt { Beginning = "My go-to comfort activity is", Continuation = "re-watching shows I know by heart while baking something I’ll eat too fast." },
            new DatingProfilePrompt { Beginning = "My most controversial opinion is", Continuation = "that naps should be mandatory for adults." },
            new DatingProfilePrompt { Beginning = "My toxic trait is thinking", Continuation = "I can assemble IKEA furniture without the instructions." },
            new DatingProfilePrompt { Beginning = "My personality in one sentence is", Continuation = "organized chaos with good snacks and strong opinions." },
            new DatingProfilePrompt { Beginning = "If my brain had tabs open, they’d be", Continuation = "memes, snacks, existential dread, and vacation planning." },
            new DatingProfilePrompt { Beginning = "I treat playlists like", Continuation = "emotional support animals." },
            new DatingProfilePrompt { Beginning = "My daily routine includes", Continuation = "forgetting my tea, remembering it cold, drinking it anyway." },
            new DatingProfilePrompt { Beginning = "My proudest adult moment so far is", Continuation = "choosing salad *and* fries and calling it balance." },
            new DatingProfilePrompt { Beginning = "If life had cheat codes, mine would be", Continuation = "‘ctrl + Z’ for awkward conversations." },
            new DatingProfilePrompt { Beginning = "My weird party trick is", Continuation = "naming that song in 3 seconds or less." }
        ];
    }
}
