version: '3.8'
services:
  postgres:
    container_name: swipe-lab-pg
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: postgres
    volumes:
      - type: bind
        source: ./data/postgres
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    container_name: swipe-lab-pgadmin
    image: dpage/pgadmin4:7
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - type: bind
        source: ./data/pgadmin
        target: /var/lib/pgadmin
    restart: unless-stopped